version: "3.8"

services:
  travel-chatbot:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Persist ChromaDB data
      - chroma_data:/app/chroma_data
      # Mount logs directory
      - ./logs:/app/logs
    environment:
      # OpenAI API Configuration
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_API_KEY_TTS=${OPENAI_API_KEY_TTS}
      - OPENAI_API_KEY_EMBEDDING=${OPENAI_API_KEY_EMBEDDING}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://aiportalapi.stu-platform.live/jpe}
      - OPENAI_MODEL_NAME=${OPENAI_MODEL_NAME:-GPT-4o-mini}

      # ChromaDB Configuration
      - CHROMA_DB_PATH=/app/chroma_data

      # Application Configuration
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  chroma_data:
    driver: local
